### PR TITLE
Feature/search condition serialization

### PR DESCRIPTION
**Pull request by sschmittBt**
Added serialization of search conditions. To allow serialization of field condition values, changed the type to JsonNode as any query will transform the value to some primitive types at execute level.

### CODE REVIEW

**Review by remi128 — CHANGES_REQUESTED** [review]
Unit-Test failure ( TestGeoSearch ); conflicts with development

**Comment by sschmittBt** [comment]
Does the test fail with TestAllMongo? Cause it works for me. Could be a difference with maven and gradle configuration. If so, please send me the failure message so I can fix it.

**Comment by remi128** [comment]
TestGeoSearch:

de.braintags.vertx.jomnigate.dataaccess.query.exception.InvalidQueryValueException: Only values that convert into primitive values, or GeoSearchArgument are allowed
	at de.braintags.vertx.jomnigate.dataaccess.query.impl.FieldCondition.validateValue(FieldCondition.java:170)
	at de.braintags.vertx.jomnigate.dataaccess.query.impl.FieldCondition.validate(FieldCondition.java:154)
	at de.braintags.vertx.jomnigate.dataaccess.query.impl.Query.setSearchCondition(Query.java:306)
	at de.braintags.vertx.jomnigate.testdatastore.TestGeoSearch.testGeoSearch(TestGeoSearch.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at io.vertx.ext.unit.junit.VertxUnitRunner.invokeTestMethod(VertxUnitRunner.java:95)
	at io.vertx.ext.unit.junit.VertxUnitRunner.lambda$invokeExplosively$0(VertxUnitRunner.java:114)
	at io.vertx.ext.unit.junit.VertxUnitRunner$$Lambda$1/1749186397.handle(Unknown Source)
	at io.vertx.ext.unit.impl.TestContextImpl$Step.run(TestContextImpl.java:122)
	at io.vertx.ext.unit.impl.TestContextImpl$Step.access$600(TestContextImpl.java:30)
	at io.vertx.ext.unit.impl.TestContextImpl.run(TestContextImpl.java:221)
	at io.vertx.ext.unit.junit.VertxUnitRunner.invokeExplosively(VertxUnitRunner.java:130)
	at io.vertx.ext.unit.junit.VertxUnitRunner.access$000(VertxUnitRunner.java:39)
	at io.vertx.ext.unit.junit.VertxUnitRunner$1.evaluate(VertxUnitRunner.java:84)
	at io.vertx.ext.unit.junit.Timeout$1.evaluate(Timeout.java:45)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at io.vertx.ext.unit.junit.VertxUnitRunner$2.evaluate(VertxUnitRunner.java:196)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Comment by remi128** [comment]
de.braintags.vertx.jomnigate.dataaccess.query.exception.InvalidQueryValueException: Only values that convert into primitive values, or GeoSearchArgument are allowed, not: {"$geometry":{"type":"Point","coordinates":[6.775763,51.224906]},"$maxDistance":10}
	at de.braintags.vertx.jomnigate.dataaccess.query.impl.FieldCondition.validateValue(FieldCondition.java:171)
	at de.braintags.vertx.jomnigate.dataaccess.query.impl.FieldCondition.validate(FieldCondition.java:154)
	at de.braintags.vertx.jomnigate.dataaccess.query.impl.Query.setSearchCondition(Query.java:306)
	at de.braintags.vertx.jomnigate.testdatastore.TestGeoSearch.testGeoSearch(TestGeoSearch.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at io.vertx.ext.unit.junit.VertxUnitRunner.invokeTestMethod(VertxUnitRunner.java:95)
	at io.vertx.ext.unit.junit.VertxUnitRunner.lambda$invokeExplosively$0(VertxUnitRunner.java:114)
	at io.vertx.ext.unit.junit.VertxUnitRunner$$Lambda$1/1058025095.handle(Unknown Source)
	at io.vertx.ext.unit.impl.TestContextImpl$Step.run(TestContextImpl.java:122)
	at io.vertx.ext.unit.impl.TestContextImpl$Step.access$600(TestContextImpl.java:30)
	at io.vertx.ext.unit.impl.TestContextImpl.run(TestContextImpl.java:221)
	at io.vertx.ext.unit.junit.VertxUnitRunner.invokeExplosively(VertxUnitRunner.java:130)
	at io.vertx.ext.unit.junit.VertxUnitRunner.access$000(VertxUnitRunner.java:39)
	at io.vertx.ext.unit.junit.VertxUnitRunner$1.evaluate(VertxUnitRunner.java:84)
	at io.vertx.ext.unit.junit.Timeout$1.evaluate(Timeout.java:45)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at io.vertx.ext.unit.junit.VertxUnitRunner$2.evaluate(VertxUnitRunner.java:196)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

**Review by remi128 — APPROVED** [review]

**Comment by remi128** [comment]
ok to be merged after resolving conflict

**Pull request merged**
